"""Initial tables

Revision ID: 8c09acf7317c
Revises: 46db5a452f3e
Create Date: 2025-08-24 22:33:04.215341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c09acf7317c'
down_revision: Union[str, None] = '46db5a452f3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('datasets', sa.Column('workflow_id', sa.Integer(), nullable=True))
    op.add_column('datasets', sa.Column('node_id', sa.String(length=100), nullable=True))
    op.add_column('datasets', sa.Column('dataset_type', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'datasets', 'workflows', ['workflow_id'], ['id'])
    op.add_column('workflows', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('workflows', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('workflows', 'progress',
               existing_type=sa.VARCHAR(),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('workflows', 'execution_time',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflows', 'execution_time',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('workflows', 'progress',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('workflows', 'completed_at')
    op.drop_column('workflows', 'started_at')
    op.drop_constraint(None, 'datasets', type_='foreignkey')
    op.drop_column('datasets', 'dataset_type')
    op.drop_column('datasets', 'node_id')
    op.drop_column('datasets', 'workflow_id')
    # ### end Alembic commands ###
