"""fix workflow id autoincrement

Revision ID: e19628b1de4b
Revises: fe41ae3204df
Create Date: 2025-08-25 22:51:12.834641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa  # noqa : 


# revision identifiers, used by Alembic.
revision: str = 'e19628b1de4b'
down_revision: Union[str, None] = 'fe41ae3204df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Ensure autoincrement is enabled on workflows.id
    op.execute("""
        ALTER TABLE workflows
        ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY
    """)


def downgrade() -> None:
    op.execute("""
        ALTER TABLE workflows
        ALTER COLUMN id DROP IDENTITY IF EXISTS
    """)
